# Do a commit every "n" Days to keep actions alive
# Adjust "n" by changing "NoOfDays" inside "Check Days"
name: KeepActionsAlive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every Day at 00:00 CET

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:

    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Check Days
      run: |
        NoOfDays=60
        LastDayOfYear=$(cat ./.github/workflows/LastDayOfYear.txt)
        CurrentDayOfYear=$(date +"%j")
        if [ $CurrentDayOfYear -lt $LastDayOfYear ]; then
          DaysInPrevYear=$(date -d "$(($(date +"%Y")-1))-12-31" +"%j")
         else
          DaysInPrevYear=0
        fi
        DaysGone=$(($CurrentDayOfYear + $DaysInPrevYear - $LastDayOfYear))
        if [ $DaysGone -ge $NoOfDays ]; then
          echo "DoIt 1"
          echo "$CurrentDayOfYear" >./.github/workflows/LastDayOfYear.txt
          echo "DoIt 2"
          git config --global user.email=${{ secrets.user_email }}
          echo "DoIt 3"
          git config --global user.name=${{ secrets.user_name }}
          echo "DoIt 4"
          git config --global user.username=${{ secrets.user_username }}
          echo "DoIt 5"
          git config --global github.user=${{ secrets.user_github_user }}
          echo "DoIt 6"
          git config --global github.token=${{ secrets.user_github_token }}
          echo "DoIt 7"
          # switching from HTTPS to SSH
          #git remote set-url origin ${{ secrets.ssh }}
          echo "DoIt 8"
          git add --all
          echo "DoIt 9"
          git commit -m "Auto updating LastDayOfYear.txt"
          echo "DoIt 10"
          git push -u origin main
          echo "DoIt 11"
        fi
