# Do a commit every "n" Days to keep actions alive
# Adjust "n" by changing "NoOfDays" inside "Check Days"
name: KeepActionsAlive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every Day at 00:00 CET

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:

    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Show Repo
      run: |
        ls -laR

    - name: Check Days
      run: |
        NoOfDays=60
        LastDayOfYear=$(cat ./.github/workflows/LastDayOfYear.txt)
        CurrentDayOfYear=$(date +"%j")
        if [ $CurrentDayOfYear -le $LastDayOfYear ]; then
          DaysInPrevYear=$(date -d "$(($(date +"%Y")-1))-12-31" +"%j")
         else
          DaysInPrevYear=0
        fi
        DaysGone=$(($CurrentDayOfYear + $DaysInPrevYear - $LastDayOfYear))
        echo "LastDayOfYear: $LastDayOfYear"
        echo "DaysInPrevYear: $DaysInPrevYear"
        echo "CurrentDayOfYear: $CurrentDayOfYear"
        echo "DaysGone: $DaysGone"
        if [ $DaysGone -ge $NoOfDays ]; then
          echo "DoIt"
        fi
