# Do a commit every "n" Days to keep actions alive
# Adjust "n" by changing "NoOfDays" inside "Check Days"
name: KeepActionsAliveByCommit

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *' # Every Day at 00:00 CET

jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: '${{ secrets.PAT }}'

    - name: Check Days
      run: |
        set -x
        set -v

        workflow="${GITHUB_WORKFLOW_REF%%@*}"
        workflow=".${workflow#${GITHUB_REPOSITORY}}"

        NoOfDays=45
        nextDayMonth=$(date -d "now + $NoOfDays Days" +"%d %m")
        sed -e "s/    - cron: .*/    - cron: '0 0 $nextDayMonth *'/" $workflow

    #- name: Commit all changed files back to the repository
    #  uses: stefanzweifel/git-auto-commit-action@v5

