# Do a commit every "n" Days to keep actions alive
# Adjust "n" by changing "NoOfDays" inside "Check Days"
name: KeepActionsAlive

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Every Day at 00:00 CET

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:

    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Show Secrects
      run: |
        echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
        echo "ssh_user: ${{ secrets.SSH_USER }}"
        echo "ssh_token: ${{ secrets.ssh_token }}"

