name: Test
on:
  workflow_dispatch:
  push:
permissions:
  actions: write
  contents: write
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        set -x
        THIS_REPO_DIR=${GITHUB_REPOSITORY##*/}
        APT_CACHE_DIR=${THIS_REPO_DIR}/cache/var/cache/apt
        TOOLS_DIR=${GITHUB_WORKSPACE}/.github/scripts
        
        for i in THIS_REPO_DIR APT_CACHE_DIR TOOLS_DIR; do
          eval "r=\"\$$i\""
          echo "$i=$r" >> $GITHUB_ENV
        done

    - name: Show
      run: |
        set -x
        for i in THIS_REPO_DIR APT_CACHE_DIR TOOLS_DIR; do
          eval "r=\"\$$i\""
          echo "$i: $r"
        done

    #- name: Clone the repository
    #  uses: actions/checkout@v4
    #  with:
    #    ref: ${{ github.head_ref }}
    #    path: '${{ env.THIS_REPO_DIR }}'

    #- name: Mod Apt
    #  run: |
    #    cd "$REPO_DIR"
    #    $TOOLS/ModApt.sh
