name: Test
on:
  workflow_dispatch:
  push:
permissions:
  actions: write
  contents: write
defaults:
  run:
    shell: bash
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Env
      run: |
        set -x
        THIS_REPO_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY##*/}
        APT_CACHE_DIR=${THIS_REPO_DIR}/cache/var/cache/apt
        TOOLS_DIR=${THIS_REPO_DIR}/.github/scripts

        for i in THIS_REPO_DIR APT_CACHE_DIR TOOLS_DIR; do
          eval "r=\"\$$i\""
          echo "$i=$r" >> $GITHUB_ENV
        done

    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        path: '${{ env.THIS_REPO_DIR }}'

    - name: Mod Apt
      run: |
        cd "$REPO_DIR"
        $TOOLS_DIR/ModApt.sh

    - name: Commit all changed files back to the repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto-Commit
        repository: ${{ env.THIS_REPO_DIR }}

    - name: Check Releases
      id: Check_Releases
      run: |
        cd "$GITHUB_WORKSPACE"
        $TOOLS_DIR/CheckReleases.sh
        if [[ "$NEW_RELEASE" == "false" ]]; then
          echo "No new release found. Exiting."
          exit 0  # Exit the job gracefully if no new release
        fi

    - name: Exit if no new release
      run: |
        if [[ -z "$NEW_RELEASE" ]]; then
          echo "No new release found. Exiting."
          exit 0  # Exit the job gracefully if no new release
        fi

