name: TestLinux
on:
  workflow_dispatch:
  push:
permissions:
  actions: write
  contents: write
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        set -x
        GITHUB_REPO="${{ github.repository }}"
        echo -e "REPO_DIR=${GITHUB_REPO##*/}" >> $GITHUB_ENV
        echo -e "REPO_DIR2=${${{ github.repository }}##*/}" >> $GITHUB_ENV

    - name: Show
      run: |
        echo GITHUB_REPO: $GITHUB_REPO
        echo GITHUB_REPO2: $GITHUB_REPO2
        


