name: TestLinux
on:
  workflow_dispatch:
permissions:
  actions: write
  contents: write
env:
  GITHUB_REPO: ${{ github.repository }}
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        set -x
        REPO_DIR="${GITHUB_REPO##*/}"
        echo -e "REPO_DIR=$REPO_DIR" >> $GITHUB_ENV
        APT_CACHE_DIR="$PWD/$REPO_DIR/cache/var/cache/apt"
        echo -e "APT_CACHE_DIR=$APT_CACHE_DIR" >> $GITHUB_ENV

    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        path: '${{ env.REPO_DIR }}'

    - name: Mod Apt
      run: |
        cd "$REPO_DIR"
        ./ModApt.sh
        
    - name: apt update
      run: |
        sudo apt update
        sudo apt install -y locales-all

    - name: Make APT_CACHE_DIR readable
      run: |
        sudo chmod a+r $APT_CACHE_DIR/archives/*
    - name: Commit all changed files back to the repository
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Auto-Commit
        repository: ${{ env.REPO_DIR }}

