name: TestArtifact

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Every 1. of Moth at 00:00 CET

jobs:
  linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:

    - name: Download tag
      uses: actions/download-artifact@v4
      with:
        name: MyTest-Tag
        path: ./MyTest-Tag
      continue-on-error: true

    - name: Set tag
      id: set_tag
      run: |
        ls -la
        TAG=0
        if [ -f ./Test-Tag/MyTest.txt ]; then
          TAG=$(cat ./Test-Tag/MyTest.txt)
          echo "TAG read: $TAG"
        else
          echo "TAG not found"
          TAG=0
        fi
        TAG=$(($TAG + 1))
        echo "TAG now: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
        if [ ! -d ./Test-Tag ]; then
          mkdir ./Test-Tag
        fi
        echo "$TAG" > ./Test-Tag/MyTest.txt

    - name: Upload tag
      uses: actions/upload-artifact@v4
      with:
        name: MyTest-Tag
        path: ./MyTest-Tag
