name: Test
on:
  workflow_dispatch:
    inputs:
      var1:
        required: true
        type: String
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    env:
      VAR1: ${{ inputs.var1 }}
    steps:
      - run: |
          echo "var1: $VAR1"

 
