name: TestLinux
on:
  workflow_dispatch:
permissions:
  actions: write
env:
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_REPO: ${{ github.repository }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        set -x;
        REPO_DIR="${GITHUB_REPO##*/}"
        echo -e "REPO_DIR=$REPO_DIR" >> $GITHUB_ENV
        APT_CACHE_DIR="$PWD/$REPO_DIR/cache/var/cache/apt"
        echo -e "APT_CACHE_DIR=$APT_CACHE_DIR" >> $GITHUB_ENV
        #declare -p

    - name: Show Env
      run: |
        set -x
        echo "REPO_DIR: $REPO_DIR"
        echo "APT_CACHE_DIR: $APT_CACHE_DIR"

    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        path: '${{ env.REPO_DIR }}'

