name: TestLinux
on:
  workflow_dispatch:
permissions:
  actions: write
env:
  GITHUB_TOKEN: ${{ github.token }}
  GITHUB_REPO: ${{ github.repository }}
  GITHUB_HEAD_REF: ${{ github.head_ref }}
defaults:
  run:
    shell: bash
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: |
        set -x;
        REPO_DIR="${GITHUB_REPO##*/}"
        echo -e "REPO_DIR=$REPO_DIR" >> $GITHUB_ENV
        APT_CACHE_DIR="$PWD/$REPO_DIR/cache/var/cache/apt"
        echo -e "APT_CACHE_DIR=$APT_CACHE_DIR" >> $GITHUB_ENV
        #declare -p

    - name: Show Env
      run: |
        set -x
        echo "REPO_DIR: $REPO_DIR"
        echo "APT_CACHE_DIR: $APT_CACHE_DIR"

    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        path: '${{ env.REPO_DIR }}'

    - name: Mod Apt
      run: |
        #set -x
        echo -e "Binary::apt::APT::Keep-Downloaded-Packages "true";\nAPT::Keep-Downloaded-Packages "true";\n" | sudo tee /etc/apt/apt.conf.d/99x-my
        if [ ! -d "$APT_CACHE_DIR" ]; then
          echo "$APT_CACHE_DIR does not exist"
          mkdir -p "$APT_CACHE_DIR"
          sudo mv /var/cache/apt/archives/ "$APT_CACHE_DIR"
         else
          echo "$APT_CACHE_DIR exists"
          sudo rm -r /var/cache/apt/archives/
        fi
        sudo ln -s "$APT_CACHE_DIR/archives/" /var/cache/apt/archives
        sudo chmod a+r $APT_CACHE_DIR/archives/*

