name: TestArtifact

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 1 * *' # Every 1. of Moth at 00:00 CET

jobs:
  linux:
    runs-on: ubuntu-24.04
    timeout-minutes: 180
    steps:

    - name: Create Tag Dir
      run: |
        if [ ! -d ./MyTest-Tag ]; then
          mkdir ./MyTest-Tag
        fi

    - name: Download tag
      uses: actions/download-artifact@v4
      with:
        name: MyTest-Tag
        path: ./MyTest-Tag/MyTag.txt
      continue-on-error: true

    - name: Set tag
      id: set_tag
      run: |
        ls -la
        ls -la ./MyTest-Tag
        TAG=0
        if [ -f ./MyTest-Tag/MyTag.txt ]; then
          TAG=$(cat ./MyTest-Tag/MyTag.txt)
          echo "TAG read: $TAG"
        else
          echo "TAG not found"
          TAG=0
        fi
        TAG=$(($TAG + 1))
        echo "TAG now: $TAG"
        echo "TAG=$TAG" >> $GITHUB_ENV
        echo "$TAG" > ./MyTest-Tag/MyTag.txt

    - name: Upload tag
      uses: actions/upload-artifact@v4
      with:
        name: MyTest-Tag
        path: ./MyTest-Tag/MyTag.txt
